### ISSUE TITLE
Build fails while trying to generate docs using Java 1.8

### ISSUE THREAD

**Issue by jrha** [quattor/maven-tools#159]
```
[INFO] Reactor Summary:
[INFO] 
[INFO] quattor maven build tools .......................... SUCCESS [  7.667 s]
[INFO] assemblies ......................................... SUCCESS [  1.522 s]
[INFO] build-scripts ...................................... SUCCESS [02:09 min]
[INFO] build-profile ...................................... SUCCESS [  0.047 s]
[INFO] quattor cfg. module archetype ...................... SUCCESS [  0.792 s]
[INFO] quattor build maven plugin ......................... FAILURE [  9.476 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:29 min
[INFO] Finished at: 2017-03-29T10:26:27+01:00
[INFO] Final Memory: 25M/287M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.7:jar (attach-javadocs) on project quattor-build-maven-plugin: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - ~/dev/maven-tools/quattor-build-maven-plugin/src/main/java/org/quattor/maven/QuattorBuild.java:17: error: unknown tag: goal
[ERROR] * @goal set-build-properties
[ERROR] ^
[ERROR] ~/dev/maven-tools/quattor-build-maven-plugin/src/main/java/org/quattor/maven/QuattorBuild.java:19: error: unknown tag: phase
[ERROR] * @phase initialize
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el6_8.x86_64/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '~/dev/maven-tools/quattor-build-maven-plugin/target/apidocs' dir.
```

Still works fine with Java 1.7.

**Comment by jouvin** [comment]
Strange... I'm sure I ran the test phase when doing my last changes... We need to bisect to identify what brought this problem.

**Comment by jrha** [comment]
Was maven using Java 1.8 when you ran the tests?

**Comment by jrha** [comment]
The same problem affects pan

**Comment by jrha** [comment]
Not just us! http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete

**Comment by jrha** [comment]
Caused by http://openjdk.java.net/jeps/172

**Comment by jrha** [comment]
For the record, the problem is that maven allows "magical" values in doc strings which are not technically valid in javadoc.

**Comment by jouvin** [comment]
I don't understand why I cannot reproduce the problem with:
```
bash-4.1$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /exp/si/jouvin/tools/apache-maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el6_8.x86_64/jre
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "2.6.32-642.6.2.el6.x86_64", arch: "amd64", family: "unix"
```

**Comment by jrha** [comment]
This was fixed by #178.
